### ISSUE TITLE
decide on core metadata fields for documents (minutes/agendas)

### ISSUE THREAD

**Issue by chooliu** [Data4Democracy/town-council#7]

**Comment by davidmooreppf** [comment]
As in other issues here, just linking to Open Civic Data [event](http://opencivicdata.readthedocs.io/en/latest/data/event.html) objects, including agenda items and minutes (as notes, I believe).

**Comment by bstarling** [comment]
After working on a prototype link scraper here are my thoughts.

Right now I believe our primary goal is to get the documents, extract the data and make them text searchable. The full Open Civic Data's schema may be overkill for our purposes since they have a much more ambitious goal of creating a full record of what local governments are doing. Meeting start time, end time etc. A lot of this required data is harder to get and without spending a lot of time on it.

I decided to go with a simplified set of fields while keeping OCD's schema in mind, we could potentially switch over at some point but in order to enforce it we would need a lot more hours dedicated to gathering/maintaining the data.

Here are the fields I'm currently using:
event name
event record date
document url 
document media type (application/pdf, text/html etc.)
document url hash
document category (minutes, agenda etc.)
(record) created_at
(record) updated_at

**Comment by chooliu** [comment]
I agree with Ben's comment--unfortunately, I think those fields are the ones consistently recorded for each city.

Things past this would be amazing, but let's revisit after we get the basic text collection (i.e., first database prototype down and/or as we get more volunteers to write scrapers.

**Comment by bstarling** [comment]
Closing, this has been documented in the crawler readme.
